# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oqtopus_engine_core/interfaces/mitigator_interface/v1/mitigator.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'oqtopus_engine_core/interfaces/mitigator_interface/v1/mitigator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEoqtopus_engine_core/interfaces/mitigator_interface/v1/mitigator.proto\x12\x16mitigator_interface.v1\"2\n\x08MesError\x12\x12\n\x04p0m1\x18\x01 \x01(\x02R\x04p0m1\x12\x12\n\x04p1m0\x18\x02 \x01(\x02R\x04p1m0\"\x95\x01\n\x05Qubit\x12\x0e\n\x02id\x18\x01 \x01(\x05R\x02id\x12\x0e\n\x02t1\x18\x02 \x01(\x02R\x02t1\x12\x0e\n\x02t2\x18\x03 \x01(\x02R\x02t2\x12\x1d\n\ngate_error\x18\x04 \x01(\x02R\tgateError\x12=\n\tmes_error\x18\x05 \x01(\x0b\x32 .mitigator_interface.v1.MesErrorR\x08mesError\"[\n\x0e\x44\x65viceTopology\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x35\n\x06qubits\x18\x02 \x03(\x0b\x32\x1d.mitigator_interface.v1.QubitR\x06qubits\"\x8e\x02\n\x14ReqMitigationRequest\x12O\n\x0f\x64\x65vice_topology\x18\x01 \x01(\x0b\x32&.mitigator_interface.v1.DeviceTopologyR\x0e\x64\x65viceTopology\x12P\n\x06\x63ounts\x18\x02 \x03(\x0b\x32\x38.mitigator_interface.v1.ReqMitigationRequest.CountsEntryR\x06\x63ounts\x12\x18\n\x07program\x18\x03 \x01(\tR\x07program\x1a\x39\n\x0b\x43ountsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\x05R\x05value:\x02\x38\x01\"\xa5\x01\n\x15ReqMitigationResponse\x12Q\n\x06\x63ounts\x18\x01 \x03(\x0b\x32\x39.mitigator_interface.v1.ReqMitigationResponse.CountsEntryR\x06\x63ounts\x1a\x39\n\x0b\x43ountsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\x05R\x05value:\x02\x38\x01\x32\x80\x01\n\x10MitigatorService\x12l\n\rReqMitigation\x12,.mitigator_interface.v1.ReqMitigationRequest\x1a-.mitigator_interface.v1.ReqMitigationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oqtopus_engine_core.interfaces.mitigator_interface.v1.mitigator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQMITIGATIONREQUEST_COUNTSENTRY']._loaded_options = None
  _globals['_REQMITIGATIONREQUEST_COUNTSENTRY']._serialized_options = b'8\001'
  _globals['_REQMITIGATIONRESPONSE_COUNTSENTRY']._loaded_options = None
  _globals['_REQMITIGATIONRESPONSE_COUNTSENTRY']._serialized_options = b'8\001'
  _globals['_MESERROR']._serialized_start=97
  _globals['_MESERROR']._serialized_end=147
  _globals['_QUBIT']._serialized_start=150
  _globals['_QUBIT']._serialized_end=299
  _globals['_DEVICETOPOLOGY']._serialized_start=301
  _globals['_DEVICETOPOLOGY']._serialized_end=392
  _globals['_REQMITIGATIONREQUEST']._serialized_start=395
  _globals['_REQMITIGATIONREQUEST']._serialized_end=665
  _globals['_REQMITIGATIONREQUEST_COUNTSENTRY']._serialized_start=608
  _globals['_REQMITIGATIONREQUEST_COUNTSENTRY']._serialized_end=665
  _globals['_REQMITIGATIONRESPONSE']._serialized_start=668
  _globals['_REQMITIGATIONRESPONSE']._serialized_end=833
  _globals['_REQMITIGATIONRESPONSE_COUNTSENTRY']._serialized_start=608
  _globals['_REQMITIGATIONRESPONSE_COUNTSENTRY']._serialized_end=665
  _globals['_MITIGATORSERVICE']._serialized_start=836
  _globals['_MITIGATORSERVICE']._serialized_end=964
# @@protoc_insertion_point(module_scope)
