services:
  estimator:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      TZ: ${TZ}
      ESTIMATOR_PORT: ${ESTIMATOR_PORT}
      ESTIMATOR_WORKERS: ${ESTIMATOR_WORKERS}
    ports:
      - ${ESTIMATOR_PORT}:${ESTIMATOR_PORT}
    volumes:
      - ./:/app
      - ${SHARE_DIR}/${LOG_DIR}:/estimator/logs
    tty: true
