# coding: utf-8

"""
    OQTOPUS Cloud Provider API

    OQTOPUS Cloud Provider API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: oqtopus-team[at]googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DevicesUpdateDeviceRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'n_qubits': 'int'
    }

    attribute_map = {
        'n_qubits': 'n_qubits'
    }

    def __init__(self, n_qubits=None):  # noqa: E501
        """DevicesUpdateDeviceRequest - a model defined in Swagger"""  # noqa: E501
        self._n_qubits = None
        self.discriminator = None
        if n_qubits is not None:
            self.n_qubits = n_qubits

    @property
    def n_qubits(self):
        """Gets the n_qubits of this DevicesUpdateDeviceRequest.  # noqa: E501


        :return: The n_qubits of this DevicesUpdateDeviceRequest.  # noqa: E501
        :rtype: int
        """
        return self._n_qubits

    @n_qubits.setter
    def n_qubits(self, n_qubits):
        """Sets the n_qubits of this DevicesUpdateDeviceRequest.


        :param n_qubits: The n_qubits of this DevicesUpdateDeviceRequest.  # noqa: E501
        :type: int
        """

        self._n_qubits = n_qubits

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DevicesUpdateDeviceRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DevicesUpdateDeviceRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
