# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from oqtopus_engine_core.interfaces.combiner_interface.v1 import combiner_pb2 as oqtopus__engine__core_dot_interfaces_dot_combiner__interface_dot_v1_dot_combiner__pb2


class CombinerServiceStub(object):
    """RPC service for circuit combiner
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Combine = channel.unary_unary(
                '/combiner_interface.v1.CombinerService/Combine',
                request_serializer=oqtopus__engine__core_dot_interfaces_dot_combiner__interface_dot_v1_dot_combiner__pb2.CombineRequest.SerializeToString,
                response_deserializer=oqtopus__engine__core_dot_interfaces_dot_combiner__interface_dot_v1_dot_combiner__pb2.CombineResponse.FromString,
                _registered_method=True)


class CombinerServiceServicer(object):
    """RPC service for circuit combiner
    """

    def Combine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CombinerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Combine': grpc.unary_unary_rpc_method_handler(
                    servicer.Combine,
                    request_deserializer=oqtopus__engine__core_dot_interfaces_dot_combiner__interface_dot_v1_dot_combiner__pb2.CombineRequest.FromString,
                    response_serializer=oqtopus__engine__core_dot_interfaces_dot_combiner__interface_dot_v1_dot_combiner__pb2.CombineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'combiner_interface.v1.CombinerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('combiner_interface.v1.CombinerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CombinerService(object):
    """RPC service for circuit combiner
    """

    @staticmethod
    def Combine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/combiner_interface.v1.CombinerService/Combine',
            oqtopus__engine__core_dot_interfaces_dot_combiner__interface_dot_v1_dot_combiner__pb2.CombineRequest.SerializeToString,
            oqtopus__engine__core_dot_interfaces_dot_combiner__interface_dot_v1_dot_combiner__pb2.CombineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
