# coding: utf-8

"""
    OQTOPUS Cloud Provider API

    OQTOPUS Cloud Provider API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: oqtopus-team[at]googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DevicesDeviceInfoUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'upload_id': 'str',
        'calibrated_at': 'datetime'
    }

    attribute_map = {
        'upload_id': 'upload_id',
        'calibrated_at': 'calibrated_at'
    }

    def __init__(self, upload_id=None, calibrated_at=None):  # noqa: E501
        """DevicesDeviceInfoUpdate - a model defined in Swagger"""  # noqa: E501
        self._upload_id = None
        self._calibrated_at = None
        self.discriminator = None
        self.upload_id = upload_id
        self.calibrated_at = calibrated_at

    @property
    def upload_id(self):
        """Gets the upload_id of this DevicesDeviceInfoUpdate.  # noqa: E501

        Upload identifier returned by the device_info upload URL endpoint.  # noqa: E501

        :return: The upload_id of this DevicesDeviceInfoUpdate.  # noqa: E501
        :rtype: str
        """
        return self._upload_id

    @upload_id.setter
    def upload_id(self, upload_id):
        """Sets the upload_id of this DevicesDeviceInfoUpdate.

        Upload identifier returned by the device_info upload URL endpoint.  # noqa: E501

        :param upload_id: The upload_id of this DevicesDeviceInfoUpdate.  # noqa: E501
        :type: str
        """
        if upload_id is None:
            raise ValueError("Invalid value for `upload_id`, must not be `None`")  # noqa: E501

        self._upload_id = upload_id

    @property
    def calibrated_at(self):
        """Gets the calibrated_at of this DevicesDeviceInfoUpdate.  # noqa: E501

        Calibration timestamp for the uploaded device_info.  # noqa: E501

        :return: The calibrated_at of this DevicesDeviceInfoUpdate.  # noqa: E501
        :rtype: datetime
        """
        return self._calibrated_at

    @calibrated_at.setter
    def calibrated_at(self, calibrated_at):
        """Sets the calibrated_at of this DevicesDeviceInfoUpdate.

        Calibration timestamp for the uploaded device_info.  # noqa: E501

        :param calibrated_at: The calibrated_at of this DevicesDeviceInfoUpdate.  # noqa: E501
        :type: datetime
        """
        if calibrated_at is None:
            raise ValueError("Invalid value for `calibrated_at`, must not be `None`")  # noqa: E501

        self._calibrated_at = calibrated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DevicesDeviceInfoUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DevicesDeviceInfoUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
