# coding: utf-8

"""
    OQTOPUS Cloud Provider API

    OQTOPUS Cloud Provider API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: oqtopus-team[at]googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DevicesDeviceInfoUploadResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'upload_id': 'str',
        'presigned_url': 'DevicesDeviceInfoUploadPresignedURL'
    }

    attribute_map = {
        'upload_id': 'upload_id',
        'presigned_url': 'presigned_url'
    }

    def __init__(self, upload_id=None, presigned_url=None):  # noqa: E501
        """DevicesDeviceInfoUploadResponse - a model defined in Swagger"""  # noqa: E501
        self._upload_id = None
        self._presigned_url = None
        self.discriminator = None
        self.upload_id = upload_id
        self.presigned_url = presigned_url

    @property
    def upload_id(self):
        """Gets the upload_id of this DevicesDeviceInfoUploadResponse.  # noqa: E501

        Upload identifier for confirming the specific device_info upload.  # noqa: E501

        :return: The upload_id of this DevicesDeviceInfoUploadResponse.  # noqa: E501
        :rtype: str
        """
        return self._upload_id

    @upload_id.setter
    def upload_id(self, upload_id):
        """Sets the upload_id of this DevicesDeviceInfoUploadResponse.

        Upload identifier for confirming the specific device_info upload.  # noqa: E501

        :param upload_id: The upload_id of this DevicesDeviceInfoUploadResponse.  # noqa: E501
        :type: str
        """
        if upload_id is None:
            raise ValueError("Invalid value for `upload_id`, must not be `None`")  # noqa: E501

        self._upload_id = upload_id

    @property
    def presigned_url(self):
        """Gets the presigned_url of this DevicesDeviceInfoUploadResponse.  # noqa: E501


        :return: The presigned_url of this DevicesDeviceInfoUploadResponse.  # noqa: E501
        :rtype: DevicesDeviceInfoUploadPresignedURL
        """
        return self._presigned_url

    @presigned_url.setter
    def presigned_url(self, presigned_url):
        """Sets the presigned_url of this DevicesDeviceInfoUploadResponse.


        :param presigned_url: The presigned_url of this DevicesDeviceInfoUploadResponse.  # noqa: E501
        :type: DevicesDeviceInfoUploadPresignedURL
        """
        if presigned_url is None:
            raise ValueError("Invalid value for `presigned_url`, must not be `None`")  # noqa: E501

        self._presigned_url = presigned_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DevicesDeviceInfoUploadResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DevicesDeviceInfoUploadResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
