# coding: utf-8

"""
    OQTOPUS Cloud Provider API

    OQTOPUS Cloud Provider API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: oqtopus-team[at]googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JobsJobStatusUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'output_files': 'list[str]',
        'message': 'str',
        'execution_time': 'float'
    }

    attribute_map = {
        'status': 'status',
        'output_files': 'output_files',
        'message': 'message',
        'execution_time': 'execution_time'
    }

    def __init__(self, status=None, output_files=None, message=None, execution_time=None):  # noqa: E501
        """JobsJobStatusUpdate - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._output_files = None
        self._message = None
        self._execution_time = None
        self.discriminator = None
        self.status = status
        if output_files is not None:
            self.output_files = output_files
        if message is not None:
            self.message = message
        if execution_time is not None:
            self.execution_time = execution_time

    @property
    def status(self):
        """Gets the status of this JobsJobStatusUpdate.  # noqa: E501


        :return: The status of this JobsJobStatusUpdate.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this JobsJobStatusUpdate.


        :param status: The status of this JobsJobStatusUpdate.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501
        allowed_values = ["running", "succeeded", "failed", "cancelled"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def output_files(self):
        """Gets the output_files of this JobsJobStatusUpdate.  # noqa: E501

        List of all S3 file keys uploaded by provider during job execution.  # noqa: E501

        :return: The output_files of this JobsJobStatusUpdate.  # noqa: E501
        :rtype: list[str]
        """
        return self._output_files

    @output_files.setter
    def output_files(self, output_files):
        """Sets the output_files of this JobsJobStatusUpdate.

        List of all S3 file keys uploaded by provider during job execution.  # noqa: E501

        :param output_files: The output_files of this JobsJobStatusUpdate.  # noqa: E501
        :type: list[str]
        """

        self._output_files = output_files

    @property
    def message(self):
        """Gets the message of this JobsJobStatusUpdate.  # noqa: E501


        :return: The message of this JobsJobStatusUpdate.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this JobsJobStatusUpdate.


        :param message: The message of this JobsJobStatusUpdate.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def execution_time(self):
        """Gets the execution_time of this JobsJobStatusUpdate.  # noqa: E501

        Execution time for quantum computation. Specify the time in seconds, including up to milliseconds.  # noqa: E501

        :return: The execution_time of this JobsJobStatusUpdate.  # noqa: E501
        :rtype: float
        """
        return self._execution_time

    @execution_time.setter
    def execution_time(self, execution_time):
        """Sets the execution_time of this JobsJobStatusUpdate.

        Execution time for quantum computation. Specify the time in seconds, including up to milliseconds.  # noqa: E501

        :param execution_time: The execution_time of this JobsJobStatusUpdate.  # noqa: E501
        :type: float
        """

        self._execution_time = execution_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobsJobStatusUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobsJobStatusUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
