# coding: utf-8

"""
    OQTOPUS Cloud Provider API

    OQTOPUS Cloud Provider API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: oqtopus-team[at]googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JobsUpdateJobInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'combined_program': 'str',
        'transpile_result': 'JobsTranspileResult',
        'result': 'JobsJobResult',
        'message': 'str'
    }

    attribute_map = {
        'combined_program': 'combined_program',
        'transpile_result': 'transpile_result',
        'result': 'result',
        'message': 'message'
    }

    def __init__(self, combined_program=None, transpile_result=None, result=None, message=None):  # noqa: E501
        """JobsUpdateJobInfo - a model defined in Swagger"""  # noqa: E501
        self._combined_program = None
        self._transpile_result = None
        self._result = None
        self._message = None
        self.discriminator = None
        if combined_program is not None:
            self.combined_program = combined_program
        if transpile_result is not None:
            self.transpile_result = transpile_result
        if result is not None:
            self.result = result
        if message is not None:
            self.message = message

    @property
    def combined_program(self):
        """Gets the combined_program of this JobsUpdateJobInfo.  # noqa: E501


        :return: The combined_program of this JobsUpdateJobInfo.  # noqa: E501
        :rtype: str
        """
        return self._combined_program

    @combined_program.setter
    def combined_program(self, combined_program):
        """Sets the combined_program of this JobsUpdateJobInfo.


        :param combined_program: The combined_program of this JobsUpdateJobInfo.  # noqa: E501
        :type: str
        """

        self._combined_program = combined_program

    @property
    def transpile_result(self):
        """Gets the transpile_result of this JobsUpdateJobInfo.  # noqa: E501


        :return: The transpile_result of this JobsUpdateJobInfo.  # noqa: E501
        :rtype: JobsTranspileResult
        """
        return self._transpile_result

    @transpile_result.setter
    def transpile_result(self, transpile_result):
        """Sets the transpile_result of this JobsUpdateJobInfo.


        :param transpile_result: The transpile_result of this JobsUpdateJobInfo.  # noqa: E501
        :type: JobsTranspileResult
        """

        self._transpile_result = transpile_result

    @property
    def result(self):
        """Gets the result of this JobsUpdateJobInfo.  # noqa: E501


        :return: The result of this JobsUpdateJobInfo.  # noqa: E501
        :rtype: JobsJobResult
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this JobsUpdateJobInfo.


        :param result: The result of this JobsUpdateJobInfo.  # noqa: E501
        :type: JobsJobResult
        """

        self._result = result

    @property
    def message(self):
        """Gets the message of this JobsUpdateJobInfo.  # noqa: E501


        :return: The message of this JobsUpdateJobInfo.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this JobsUpdateJobInfo.


        :param message: The message of this JobsUpdateJobInfo.  # noqa: E501
        :type: str
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobsUpdateJobInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobsUpdateJobInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
