# coding: utf-8

"""
    OQTOPUS Cloud Provider API

    OQTOPUS Cloud Provider API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: oqtopus-team[at]googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JobsUpdateJobInfoRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'overwrite_status': 'JobsJobStatus',
        'execution_time': 'float',
        'job_info': 'JobsUpdateJobInfo'
    }

    attribute_map = {
        'overwrite_status': 'overwrite_status',
        'execution_time': 'execution_time',
        'job_info': 'job_info'
    }

    def __init__(self, overwrite_status=None, execution_time=None, job_info=None):  # noqa: E501
        """JobsUpdateJobInfoRequest - a model defined in Swagger"""  # noqa: E501
        self._overwrite_status = None
        self._execution_time = None
        self._job_info = None
        self.discriminator = None
        if overwrite_status is not None:
            self.overwrite_status = overwrite_status
        if execution_time is not None:
            self.execution_time = execution_time
        if job_info is not None:
            self.job_info = job_info

    @property
    def overwrite_status(self):
        """Gets the overwrite_status of this JobsUpdateJobInfoRequest.  # noqa: E501


        :return: The overwrite_status of this JobsUpdateJobInfoRequest.  # noqa: E501
        :rtype: JobsJobStatus
        """
        return self._overwrite_status

    @overwrite_status.setter
    def overwrite_status(self, overwrite_status):
        """Sets the overwrite_status of this JobsUpdateJobInfoRequest.


        :param overwrite_status: The overwrite_status of this JobsUpdateJobInfoRequest.  # noqa: E501
        :type: JobsJobStatus
        """

        self._overwrite_status = overwrite_status

    @property
    def execution_time(self):
        """Gets the execution_time of this JobsUpdateJobInfoRequest.  # noqa: E501

        Execution time for quantum computation. Specify the time in seconds, including up to milliseconds.  # noqa: E501

        :return: The execution_time of this JobsUpdateJobInfoRequest.  # noqa: E501
        :rtype: float
        """
        return self._execution_time

    @execution_time.setter
    def execution_time(self, execution_time):
        """Sets the execution_time of this JobsUpdateJobInfoRequest.

        Execution time for quantum computation. Specify the time in seconds, including up to milliseconds.  # noqa: E501

        :param execution_time: The execution_time of this JobsUpdateJobInfoRequest.  # noqa: E501
        :type: float
        """

        self._execution_time = execution_time

    @property
    def job_info(self):
        """Gets the job_info of this JobsUpdateJobInfoRequest.  # noqa: E501


        :return: The job_info of this JobsUpdateJobInfoRequest.  # noqa: E501
        :rtype: JobsUpdateJobInfo
        """
        return self._job_info

    @job_info.setter
    def job_info(self, job_info):
        """Sets the job_info of this JobsUpdateJobInfoRequest.


        :param job_info: The job_info of this JobsUpdateJobInfoRequest.  # noqa: E501
        :type: JobsUpdateJobInfo
        """

        self._job_info = job_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobsUpdateJobInfoRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobsUpdateJobInfoRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
