# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from oqtopus_engine_core.interfaces.estimator_interface.v1 import estimator_pb2 as oqtopus__engine__core_dot_interfaces_dot_estimator__interface_dot_v1_dot_estimator__pb2


class EstimatorServiceStub(object):
    """RPC service for Estimation Job
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReqEstimationPreProcess = channel.unary_unary(
                '/estimator_interface.v1.EstimatorService/ReqEstimationPreProcess',
                request_serializer=oqtopus__engine__core_dot_interfaces_dot_estimator__interface_dot_v1_dot_estimator__pb2.ReqEstimationPreProcessRequest.SerializeToString,
                response_deserializer=oqtopus__engine__core_dot_interfaces_dot_estimator__interface_dot_v1_dot_estimator__pb2.ReqEstimationPreProcessResponse.FromString,
                _registered_method=True)
        self.ReqEstimationPostProcess = channel.unary_unary(
                '/estimator_interface.v1.EstimatorService/ReqEstimationPostProcess',
                request_serializer=oqtopus__engine__core_dot_interfaces_dot_estimator__interface_dot_v1_dot_estimator__pb2.ReqEstimationPostProcessRequest.SerializeToString,
                response_deserializer=oqtopus__engine__core_dot_interfaces_dot_estimator__interface_dot_v1_dot_estimator__pb2.ReqEstimationPostProcessResponse.FromString,
                _registered_method=True)


class EstimatorServiceServicer(object):
    """RPC service for Estimation Job
    """

    def ReqEstimationPreProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReqEstimationPostProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EstimatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReqEstimationPreProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.ReqEstimationPreProcess,
                    request_deserializer=oqtopus__engine__core_dot_interfaces_dot_estimator__interface_dot_v1_dot_estimator__pb2.ReqEstimationPreProcessRequest.FromString,
                    response_serializer=oqtopus__engine__core_dot_interfaces_dot_estimator__interface_dot_v1_dot_estimator__pb2.ReqEstimationPreProcessResponse.SerializeToString,
            ),
            'ReqEstimationPostProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.ReqEstimationPostProcess,
                    request_deserializer=oqtopus__engine__core_dot_interfaces_dot_estimator__interface_dot_v1_dot_estimator__pb2.ReqEstimationPostProcessRequest.FromString,
                    response_serializer=oqtopus__engine__core_dot_interfaces_dot_estimator__interface_dot_v1_dot_estimator__pb2.ReqEstimationPostProcessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'estimator_interface.v1.EstimatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('estimator_interface.v1.EstimatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EstimatorService(object):
    """RPC service for Estimation Job
    """

    @staticmethod
    def ReqEstimationPreProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estimator_interface.v1.EstimatorService/ReqEstimationPreProcess',
            oqtopus__engine__core_dot_interfaces_dot_estimator__interface_dot_v1_dot_estimator__pb2.ReqEstimationPreProcessRequest.SerializeToString,
            oqtopus__engine__core_dot_interfaces_dot_estimator__interface_dot_v1_dot_estimator__pb2.ReqEstimationPreProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReqEstimationPostProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estimator_interface.v1.EstimatorService/ReqEstimationPostProcess',
            oqtopus__engine__core_dot_interfaces_dot_estimator__interface_dot_v1_dot_estimator__pb2.ReqEstimationPostProcessRequest.SerializeToString,
            oqtopus__engine__core_dot_interfaces_dot_estimator__interface_dot_v1_dot_estimator__pb2.ReqEstimationPostProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
