# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oqtopus_engine_core/interfaces/sse_interface/v1/sse.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'oqtopus_engine_core/interfaces/sse_interface/v1/sse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9oqtopus_engine_core/interfaces/sse_interface/v1/sse.proto\x12\x10sse_interface.v1\"-\n\x10SseEngineRequest\x12\x19\n\x08job_json\x18\x01 \x01(\tR\x07jobJson\"`\n\x11SseEngineResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n\x08job_json\x18\x02 \x01(\tR\x07jobJson\x12\x18\n\x07message\x18\x03 \x01(\tR\x07message2h\n\x10SseEngineService\x12T\n\tSseEngine\x12\".sse_interface.v1.SseEngineRequest\x1a#.sse_interface.v1.SseEngineResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oqtopus_engine_core.interfaces.sse_interface.v1.sse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SSEENGINEREQUEST']._serialized_start=79
  _globals['_SSEENGINEREQUEST']._serialized_end=124
  _globals['_SSEENGINERESPONSE']._serialized_start=126
  _globals['_SSEENGINERESPONSE']._serialized_end=222
  _globals['_SSEENGINESERVICE']._serialized_start=224
  _globals['_SSEENGINESERVICE']._serialized_end=328
# @@protoc_insertion_point(module_scope)
