# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from oqtopus_engine_core.interfaces.sse_interface.v1 import sse_pb2 as oqtopus__engine__core_dot_interfaces_dot_sse__interface_dot_v1_dot_sse__pb2


class SseEngineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SseEngine = channel.unary_unary(
                '/sse_interface.v1.SseEngineService/SseEngine',
                request_serializer=oqtopus__engine__core_dot_interfaces_dot_sse__interface_dot_v1_dot_sse__pb2.SseEngineRequest.SerializeToString,
                response_deserializer=oqtopus__engine__core_dot_interfaces_dot_sse__interface_dot_v1_dot_sse__pb2.SseEngineResponse.FromString,
                _registered_method=True)


class SseEngineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SseEngine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SseEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SseEngine': grpc.unary_unary_rpc_method_handler(
                    servicer.SseEngine,
                    request_deserializer=oqtopus__engine__core_dot_interfaces_dot_sse__interface_dot_v1_dot_sse__pb2.SseEngineRequest.FromString,
                    response_serializer=oqtopus__engine__core_dot_interfaces_dot_sse__interface_dot_v1_dot_sse__pb2.SseEngineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sse_interface.v1.SseEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sse_interface.v1.SseEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SseEngineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SseEngine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sse_interface.v1.SseEngineService/SseEngine',
            oqtopus__engine__core_dot_interfaces_dot_sse__interface_dot_v1_dot_sse__pb2.SseEngineRequest.SerializeToString,
            oqtopus__engine__core_dot_interfaces_dot_sse__interface_dot_v1_dot_sse__pb2.SseEngineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
