services:
  slurmctld:
    volumes:
      - ${OQTOPUS_ENGINE_ROOT:?OQTOPUS_ENGINE_ROOT must be set}/.cache/oqtopus-slurm-work:${OQTOPUS_ENGINE_ROOT}/.cache/oqtopus-slurm-work
      - ${OQTOPUS_ENGINE_ROOT}/test-infra/scheduler/slurm:${OQTOPUS_ENGINE_ROOT}/test-infra/scheduler/slurm:ro
      - ${OQTOPUS_ENGINE_ROOT}/deployment/slurm:${OQTOPUS_ENGINE_ROOT}/deployment/slurm:ro

  cpu-worker:
    volumes:
      - ${OQTOPUS_ENGINE_ROOT}/.cache/oqtopus-slurm-work:${OQTOPUS_ENGINE_ROOT}/.cache/oqtopus-slurm-work
      - ${OQTOPUS_ENGINE_ROOT}/test-infra/scheduler/slurm:${OQTOPUS_ENGINE_ROOT}/test-infra/scheduler/slurm:ro
      - ${OQTOPUS_ENGINE_ROOT}/deployment/slurm:${OQTOPUS_ENGINE_ROOT}/deployment/slurm:ro
