services:
  mitigator:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      TZ: ${TZ}
      MITIGATOR_PORT: ${MITIGATOR_PORT}
      MITIGATOR_WORKERS: ${MITIGATOR_WORKERS}
    ports:
      - ${MITIGATOR_PORT}:${MITIGATOR_PORT}
    volumes:
      - ./:/app
      - ${SHARE_DIR}/${LOG_DIR}:/mitigator/logs
    tty: true
