openapi: 3.0.1
info:
  title: OQTOPUS Cloud Provider API
  version: '1.0'
  contact:
    name: oqtopus-team
    email: oqtopus-team[at]googlegroups.com
  description: OQTOPUS Cloud Provider API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8888
    description: Local server url
security:
  - ApiKeyAuth: []
paths:
  /devices/{device_id}:
    $ref: ./paths/devices.yaml#/devices.device
  /devices/{device_id}/status:
    $ref: ./paths/devices.yaml#/devices.device_status
  /devices/{device_id}/device_info:
    $ref: ./paths/devices.yaml#/devices.device_info
  /jobs:
    $ref: ./paths/jobs.yaml#/jobs
  /jobs/{job_id}:
    $ref: ./paths/jobs.yaml#/jobs.job_id
  /jobs/{job_id}/status:
    $ref: ./paths/jobs.yaml#/jobs.job_status
  /jobs/{job_id}/job_info:
    $ref: ./paths/jobs.yaml#/jobs.job_info
  /jobs/{job_id}/transpiler_info:
    $ref: ./paths/jobs.yaml#/jobs.job_id.transpiler_info
  /jobs/{job_id}/ssesrc:
    $ref: ./paths/jobs.yaml#/jobs.job_id.sse_src
  /jobs/{job_id}/sselog:
    $ref: ./paths/jobs.yaml#/jobs.job_id.sse_log
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
