[estimation]
estimator_port = 502
estimator_host = "example.com"
[run_group]
  [run_group.periodic_tasks]
    [run_group.periodic_tasks.poller]
    period = "500ms"
      [run_group.periodic_tasks.poller.params]
      enable_test_mode = true
      edge = "polling_test_edge"
      device = "polling_test_device"
      endpoint = "https://example.com/v1"
      normal_period = "500ms"
      idle_period = "500ms"
    [run_group.periodic_tasks.version_log]
    period = "10s"
    [run_group.periodic_tasks.metrics_log]
    period = "10s"
      [run_group.periodic_tasks.metrics_log.params]
      file_dir = "/shares/metrics"

[com]
  [com.tranqu]
  host = "localhost"
  port = "9234"
  [com.mitigation]
  host = "localhost"
  port = "5011"
  [com.estimation]
  host = "localhost"
  port = "5012"
  [com.gateway]
  gateway_host = "localhost"
  gateway_port = "50051"
  api_endpoint = "https://example.com/v1"
  api_key = "secret_api_key"
  device_id = "your_device_id"
